# server port cfg
server:
  port: 8083
# Datasource cfg
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/samplePayment
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA cfg
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  #Config server
  config:
    import: configserver:http://localhost:9296